assembly_info:
  patch: false

configuration:
  - Debug

build_script:
  - ps: .\build.ps1 --gitHubToken=$env:GitHubToken

image: Visual Studio 2017
test: off
skip_tags: true

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
