name: Test Code

# This workflow is for testing the code.
# Because of failed permissions all steps which are pushing code to github releases or nuget are removed.
# For creating draft release launch workflow -Create Draft Release- manually.

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Avoid pre-populating the NuGet package cache

    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      checks: write #test-reporter https://github.com/dorny/test-reporter/issues/229

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install SQL CE 📅
        shell: powershell
        run: ./install-sql-ce.ps1

      - name: Cake Build 🏗️
        id: cake-build
        shell: powershell
        run: ./build.ps1
        env:
          OCTOVERSION_CurrentBranch: ${{ github.ref }}

      - name: Test Report 🧪
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Tests
          path: artifacts/TestResults/*.trx
          reporter: dotnet-trx
